name: glados-daily-checkin

on:
  workflow_dispatch: 
  schedule: 
    - cron: '21 10 * * *' 

jobs:
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }} 
    steps:
    - id: check
      run: | 
      
  run-daily-task:
    runs-on: ubuntu-latest
    environment: Production
    needs: pre-check

    steps:
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Task
      run: |
        curl -s -o /dev/null -w "%{http_code}\n" 'https://glados.cloud/api/user/checkin' -H 'accept: application/json, text/plain, */*' -H 'accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' -H 'content-type: application/json;charset=UTF-8' -b ${{secrets.COOKIES}} -H 'origin: https://glados.cloud' -H 'priority: u=1, i' -H 'sec-ch-ua: "Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"' -H 'sec-ch-ua-mobile: ?0' -H 'sec-ch-ua-platform: "Windows"' -H 'sec-fetch-dest: empty' -H 'sec-fetch-mode: cors' -H 'sec-fetch-site: same-origin' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36' --data-raw '{"token":"glados.cloud"}'
