name: bilibili-daily-task

on:
  workflow_dispatch:
  schedule:
    - cron: '20 10 * * *'

jobs:
  run-daily-task:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Test APP
      run: |
        wget https://github.com/Zhouqwq/BiliBiliToolPro/releases/download/GA/GA.zip
        unzip -P ${{secrets.PWD}} GA.zip
        cd ./linux-x64/
        sudo chmod +x ./Ray.BiliBiliTool.Console
        sudo ./Ray.BiliBiliTool.Console
        curl -s -o /dev/null -w "%{http_code}\n" 'https://glados.cloud/api/user/checkin' -H 'accept: application/json, text/plain, */*' -H 'accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' -H 'content-type: application/json;charset=UTF-8' -b ${{secrets.COOKIES}} -H 'origin: https://glados.cloud' -H 'priority: u=1, i' -H 'sec-ch-ua: "Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"' -H 'sec-ch-ua-mobile: ?0' -H 'sec-ch-ua-platform: "Windows"' -H 'sec-fetch-dest: empty' -H 'sec-fetch-mode: cors' -H 'sec-fetch-site: same-origin' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36' --data-raw '{"token":"glados.cloud"}'
